### ISSUE TITLE
Building lists with repeat

### ISSUE THREAD

**Issue by kingdase** [birchb1024/yamp#1]
Hello Peter,

this is my input to yamp:
```
- define:
    tiles:  [isolation-segment , metrics , rabbitmq ]
---
- name: start-all-pcf-automation-tasks
  plan:


  - get: bbr-om-installation-pipelinetask
    trigger: true
  - get: pcf-automation-image
    passed: [get-new-resources]

    repeat:
      for: tile
      in: tiles
      body:
         get: '{{tile}}-s3'
         passed: '[get-new-resources]'


```
This is the resulting output:
```
- name: start-all-pcf-automation-tasks
  plan:
  - get: bbr-om-installation-pipelinetask
    trigger: true
  - - get: isolation-segment-s3
      passed: '[get-new-resources]'
    - get: metrics-s3
      passed: '[get-new-resources]'
    - get: rabbitmq-s3
      passed: '[get-new-resources]'
```
And this is what i want:
```
- name: start-all-pcf-automation-tasks
  plan:
  - get: bbr-om-installation-pipelinetask
    trigger: true
  - get: isolation-segment-s3
    passed: '[get-new-resources]'
  - get: metrics-s3
    passed: '[get-new-resources]'
  - get: rabbitmq-s3
    passed: '[get-new-resources]'

```

Is this possible with yamp ? I played with flatten , but this does't work with repeat.

**Comment by birchb1024** [comment]
Hi
Yes I have added your example to a file in GitHub: [ flatten-repeat.yaml](https://raw.githubusercontent.com/birchb1024/yamp/master/examples/flatten-repeat.yaml)

It produces:
```
- name: start-all-pcf-automation-tasks
  plan:
  - get: bbr-om-installation-pipelinetask
    trigger: true
  - get: isolation-segment-s3
    passed: '[get-new-resources]'
  - get: metrics-s3
    passed: '[get-new-resources]'
  - get: rabbitmq-s3
    passed: '[get-new-resources]'
  - get: pcf-automation-image-s3
    passed: '[get-new-resources]'

```

I hope that's what you wanted?
