### ISSUE TITLE
range: over keys of a map?

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/yamp#10]
Like in goyamp, range would convert a map to a sequence of keys and return them, typically used in iterations. Here's an example, `range: all` produces a sequence from the map held in the `all` variable. (`perf` and `prod`). The macro then uses the loop variable `item` to select one of the map entries using dot notation `all.item`.   

```
- defmacro:
    name: loopy
    args: all
    value:
       repeat:
         for: item
         in: { range: all }
         body:
           env: item
           host: all.item.host
---
loopy:
  perf:
    host: lp123123
    size: 190
  prod:
    host: lpp23423
    size: 324
```
This yields

```
- env: perf
  host: lp123123
- env: prod
  host: lpp23423
```
