### ISSUE TITLE
Feature Request: ifdef directive starts a section of conditionally compiled code

### ISSUE THREAD

**Issue by kingdase** [birchb1024/yamp#11]
It would be great to use ifdef to remove whole blocks in yaml.
I tried the if statement, but it does not work.

We have code blocks in our concourse pipeline that involve staging, and they're not needed in production stage because it's the final stage.

We use the same pipeline code for all stages.

As a workaround I use begin / end comments and suppress the enclosing lines with awk before calling yamp.

the ifdef statement should, if possible, query the environemnt.

e.g.
```
ifdef: { python_eval: 'env["stage"]  != "prod"' }
...
endif
```

Enclosed a section of our pipeline with the mentioned comments

```
---
groups:
- name: pcf-automation
  jobs:
    flatten:
      - get-new-resources
      - check-runned-om-installation-pipelinetask-opsmgr
      - check-runned-backup-ert-pipelinetask-opsmgr
      - check-runned-backup-director-pipelinetask-opsmgr
      - create-infrastructure
      - run-p-smoketests
      - pause-pipelines
      - unpause-pipelines
      - configure-director
      - apply-product-changes
      - run-p-smoketest-after-deployment
      - upload-stemcells

# START NOT-IN-PROD
      - promote-opsmgr
      - repeat:
          for: tile
          in: stems
          body:
            - promote-{{tile.name}}

      - promote-platform-automation
      - promote-pas
# END NOT-IN-PROD

      - upgrade-opsman
      - extend-opsman-vm-types

      - upload-and-stage-pas
      - configure-pas

      - repeat:
          for: tile
          in: tilex
          body:
            - upload-and-stage-{{tile.name}}
            - configure-{{tile.name}}
# START NOT-IN-PROD
            - promote-{{tile.name}}
# END NOT-IN-PROD


- name: config-and-maintenance
  jobs:
  - start-all-pcf-automation-tasks
# START NOT-IN-PROD
  - promote-all
# END NOT-IN-PROD
  - create-infrastructure-manual


resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

```
