### ISSUE TITLE
Feature Request: Allow builtin macros to be redefined/renamed

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/yamp#3]
In case of a name collision with the target language, this will allow any arbitrary names to be used.
e.g.

```
- define: 
    deeplist:  [[[6,7]]]
    renamed: flatone
- renamed: [1, 2, [3], [[4, 5]],  deeplist]
```
