### ISSUE TITLE
is there a path reference?

### ISSUE THREAD

**Issue by lgfausak** [birchb1024/yamp#5]
feature request:  it would be really handy to know where i am in the yaml text.  For example:

```
- defmacro:
    name: MACRO
    args: [ arg1 ]
    value: arg1
---
one:
  two:
    data: { MACRO: { arg1: '$PATH' } }
```

The output would look something like:

```
one:
  two:
    data one.two.data
```

I could use that value in python_eval to do a variety of stuff if I knew where I was in the yaml.  I am thinking you must know where you are, because the yaml is expanded at that point.

**Comment by birchb1024** [comment]
Hi,
I think I understand what you're asking. However, can you give me an example of where you would use the facility? 
Regards,
BB

**Comment by lgfausak** [comment]
wherever i am in the tree, it would be nice to be able to make a reference relative to that.  so, like .my_boolean, for example would reference the attribute my_boolean whereever we currently are in the yaml tree.  if you are familiar with jq (json query) the dot (.) operator is what i'm talking about.  in jq everything is referenced relative to wherever you are currently processing.  Currently we have the ability to reference anything in a yaml file with an absolute reference (starting from the root).  it would be nice to be able to start referencing relatively (like a relative vs. absolute file reference from the shell).  Like the jq . (dot) operator.  perhaps if the current 'tree' was presented to the python_eval builtin bound to a local variable called CUR, I could reference CUR.attribute from a python_eval() call.  That would do it.  Something else I toyed with was adding a stack to expand(tree,binding), everytime it sees a new dict tree it pushes the current 'name' to the stack.  Then have a new builtin that retrieves the current stack, joined with dots, which would give you the absolute path in the current tree.  I couldn't make it work though.  the arrays were messing me up.

**Comment by birchb1024** [comment]
Thanks. I'm struggling to understand how a downstream application would _use_ a reference like that. Please can you make this less abstract? I mean what kind of YAMLs are you working with? Myself I work with GoCD pipeline YAML, Kubernetes manifests (Helm) and ansible inventory YAML. All of these are fundamentally simple, they only need string values, but lots of them ;-) It would help me understand your requirement better if you could give some background. Perhaps push some real example code somewhere? Cheers.

**Comment by lgfausak** [comment]
Real example code is hard because there is nothing that really does this.  Your code can, the expand function can create a stack indicating where it is in the yaml tree being processed.  I have taken some stabs at coding this.  I have nothing working yet, but I will continue to try.  The concept is fairly simple, I would like to be able to access the current tree based on relative references.  I did mention the jq code [jq:](https://stedolan.github.io/jq/) . The way jq references the json data is always relative.

It sounds like we are doing very similar work.  I am working with ansible, jinja templates, cicd, nomad, consul, everything runs on json/yaml.  So, I basically take a yaml description I have, and use yamp (or jinja, or jq) to massage it in to a different format for something else to consume.

Here is some pseudo code (very contrived) for what I am talking about:

data
```
# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
- defmacro:
    name: CIDR4-OFFSET
    args: [ NET, INC ]
    value: { python_eval: 'str(ipaddress.IPv4Network(unicode(NET)).network_address + INC)' }
---
# this works, but each ip: line is different:
hosts:
  h1:
    network: 10.20.30.128/25
    offset: 5
    ip: CIDR4-OFFSET(hosts.h1.network,hosts.h1.offset)
  h2:
    network: 10.20.30.128/25
    offset: 6
    ip: CIDR4-OFFSET(hosts.h2.network,hosts.h2.offset)

---
# with a relative reference the ip: line would be the same
hosts:
  h1:
    network: 10.20.30.128/25
    offset: 5
    ip: CIDR4-OFFSET($.network,$.offset)
  h2:
    network: 10.20.30.128/25
    offset: 6
    ip: CIDR4-OFFSET($.network,$.offset)
```
 Although this is a dumb example it shows how I can drop a line of text in to any of the host stanzas without 'knowing' where it is.

Even having access to the root of the current tree in a python_eval (or the upcoming exec ;-) ) would be super handy.  I realize I am having a hard time making my case, but I think this would be a game changer.

Here is a [jsonpath](https://goessner.net/articles/JsonPath/)   reference.  I don't personally use jsonpath, but they do show some syntax that might be useful.

I rest my case.  Have a great weekend (I think you are already experiencing Sat Night, Sat morning here in Texas).

**Comment by birchb1024** [comment]
I see. Have you tried ranging over hosts:

````
repeat:
   for: $hostname
   in: {range: hosts}
   key: $hostname
   body:
         network: hosts.$hostname.network
         offset: hosts.$hostname.offset
         ip: {cidr-offset: {net: hosts.$hostname.network, off: hosts.$hostname.offset}
````
Worth a try

**Comment by lgfausak** [comment]
i use that technique.  it does work, however, you need to know where you are in the schema to do that.  i have multiple 'records' like hosts that have a network and an offset.  something like:
```
repeat:
  for: $key
  in: { range: . }
  body:
    ...
```
is the spell I seek.  I will take a stab at it again in the future. thx.
