### ISSUE TITLE
if eager evaluation

### ISSUE THREAD

**Issue by lgfausak** [birchb1024/yamp#6]
i hit some unexpected behavior with an if: then: else:.  Consider:
```
- define: {x: { one: 1, two: 2 } }
- defmacro:
    name: PRINTNUM
    args: [ data ]
    value: { if: { python_eval: 'data == "ONE"' }, then: x.one, else: x.two }
---
{ "output": { "test": { PRINTNUM: { data: "TWO" } } } }
```
running yamp:
```
$ yamp g.yaml 
output:
  test: 2
```
However, if the data is not there, then it gets an error:
```
- define: {x: { two: 2 } }
- defmacro:
    name: PRINTNUM
    args: [ data ]
    value: { if: { python_eval: 'data == "ONE"' }, then: x.one, else: x.two }
---
{ "output": { "test": { PRINTNUM: { data: "TWO" } } } }
```
and the output:
```
$ yamp g.yaml 
ERROR: /home/install/git/vcp2-inv/data/tpa-lab-1/g.yaml
<class '__main__.YampException'>
Subvariable "one" not found in x.one
```
It seems that both then: and else: are resolved before if: is tested
