### ISSUE TITLE
python_eval unable to access all macro defined variables

### ISSUE THREAD

**Issue by lgfausak** [birchb1024/yamp#7]
the arguments in a macro are not reference-able if the macro does a repeat.  For example:

```
- defmacro:
    name: TESTARG
    args: [ FIRST ]
    value:
      { data: { if: { python_eval: '1 == FIRST' }, then: "equals one", else: "not equals one" } }
---
- { TESTARG: { FIRST: 0 } }
```
when I run this script, I get:
```
- data: not equals one
```
Note: the FIRST argument is being referenced in the python_eval.  Now consider this:
```
- defmacro:
    name: TESTARG
    args: [ FIRST ]
    value:
      - repeat:
          for: rux
          in: { range: [ 1, 4 ] }
          body:
            - { data: { if: { python_eval: 'rux == FIRST' }, then: "equals one", else: "not equals one" } }
#            - { "rux": rux, data: FIRST }
---
- { TESTARG: { FIRST: 2 } }
```
when I run this script, I get this error:
```
<type 'exceptions.NameError'>
name 'FIRST' is not defined
```
If I comment out the python_eval and uncomment the data: FIRST:
```
- defmacro:
    name: TESTARG
    args: [ FIRST ]
    value:
      - repeat:
          for: rux
          in: { range: [ 1, 4 ] }
          body:
#            - { data: { if: { python_eval: 'rux == FIRST' }, then: "equals one", else: "not equals one" } }
            - { "rux": rux, data: FIRST }
---
- { TESTARG: { FIRST: 2 } }
```
I now see this result:
```
- - - - data: 2
        rux: 1
    - - data: 2
        rux: 2
    - - data: 2
        rux: 3
    - - data: 2
        rux: 4
```
I guess this has something to do with . nesting a macro and trying to reference parent data?

**Comment by birchb1024** [comment]
Hi Greg, 
I'm going to respond RFTM on this one ;-) (wink) Quote the manual _"Python cannot see bindings in the environment hierarchy directly"_. `python_eval` is _only_ there to provide more complex math and other fundamentals the macro processor does not have.  So python eval() does not search the tree of closures looking for variables bound in earlier macro definitions or repeat scopes. 

The good news is you don't need to use python_eval to to get bindings resolved. The code below produces the results you expect without python_eval.   

> Sidenote: The Go version of Yamp 'goyamp',  does not have a Python interpreter to hand so I am building an 'execute:'  builtin to fork a subprocess and transfer YAML/JSON in and out.. Maybe I will backport `execute:` into Yamp also. But I digress

```
- defmacro:
    name: TESTARG
    args: [ FIRST ]
    value:
      repeat:
          for: rux
          in: { range: [ 1, 4 ] }
          body:
            if: { ==: [rux, FIRST] }
            then: "{{rux}} equals {{FIRST}}"
            else: "{{rux}} not equals {{FIRST}}"
---
TESTARG: { FIRST: 2 }
```
This gives :

```
---
- 1 not equals 2
- 2 equals 2
- 3 not equals 2
- 4 not equals 2
```
