### ISSUE TITLE
execute: builtin for sub-processes? 

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/yamp#9]
TLDW
```
# Get public IP address 
define:
   public_ip: 
       execute:
            command: curl
            args: https://api.ipify.org/?format=json
```
- Automatically parses YAML/JSON in stdout
- `environment:` to specify environment variables for the process
- `data:` to specify JSON to send to stdin of process
- `directory:` to specify current dir for process 

(A Goyamp backport)
